[package]
name = "niter"
version = "0.0.0"
description = "A CLI tool for managing and packing Minecraft modpacks"
repository = "https://github.com/panda885/niter"
license = "MIT OR Apache-2.0"
authors = ["Panda885"]
categories = ["command-line-utilities"]
keywords = ["Minecraft", "modpack"]
readme = "README.md"
edition = "2021"

[dependencies]
clap = { version = "4.1.6", features = ["cargo"] }
futures = "0.3.26"
reqwest = { version = "0.11.14", features = ["blocking"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
termcolor = "1.2.0"
